# IP Range: 172.30.1.51-60
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: 'reverse-proxy'
    healthcheck:
      test: ['CMD', '/gluetun', 'healthcheck']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=mI6PYEzEUpcvrSb5AE/phDWVKgJ7UqltSddgYDgr6mM=
      - WIREGUARD_PRESHARED_KEY=pRLLJWJ+3qU9t/JdQElAdczpRWM2Tx40RHHdiSUaJgk=
      - WIREGUARD_ADDRESSES=10.168.1.231/32
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL_VPN_INPUT_PORTS=59972
      - FIREWALL_OUTBOUND_SUBNETS=172.30.1.0/24,192.168.1.0/24
      - DOT_PROVIDERS=cloudflare # or other provider (google, quad9, etc.)
      - DOT_DNS_ADDRESS=1.1.1.1 # or other DNS address
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
    ports:
      - 8888:8888/tcp
      - 8388:8388/udp
      - 8388:8388/tcp
      - 3000:3000
      - 3001:3001
      - 8080:8080 # qBittorrent webui port
      - 59972:59972 # qBittorrent torrent port
      - 59972:59972/udp # qBittorrent torrent port

  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - NAME_SERVERS=1.1.1.1
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.52

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: 'service:gluetun'
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/prowlarr-config:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.2-r0-ls367
    container_name: qbittorrent-vpn
    depends_on:
      - gluetun
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    #      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /plex-stack-config/config/qbittorrent-config:/config
      - /mnt/plex-stack/data/torrents:/data/torrents
    network_mode: 'service:gluetun'
    restart: unless-stopped

  # TODO fix manual categories that should never be removed
  qbit-manage:
    container_name: qbit-manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    volumes:
      - /plex-stack-config/config/qbit-manage/:/config:rw
      - /mnt/plex-stack/data/torrents:/data/torrents:rw
      - /plex-stack-config/config/qbittorrent-config/:/qbittorrent/:ro
    environment:
      - QBT_RUN=false
      - QBT_SCHEDULE=1440
      - QBT_CONFIG=config.yml
      - QBT_LOGFILE=activity.log
      - QBT_CROSS_SEED=false
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=false
      - QBT_TAG_UPDATE=false
      - QBT_REM_UNREGISTERED=false
      - QBT_REM_ORPHANED=false
      - QBT_TAG_TRACKER_ERROR=false
      - QBT_TAG_NOHARDLINKS=false
      - QBT_SHARE_LIMITS=false
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=true
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
    restart: on-failure:2
    networks:
      default:
        ipv4_address: 172.30.1.53
  # upload-assistant:
  #   image: ghcr.io/audionut/upload-assistant:master
  #   network_mode: 'reverse-proxy'
  #   volumes:
  #     - /plex-stack-config/config/upload-assistant/config.py:/Upload-Assistant/data/config.py
  #     - /mnt/plex-stack/data:/data
  #   #      - /mnt/plex-stack/data/torrents/BT_backup:/BT_backup
  #   stdin_open: true
  #   tty: true

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=/etc/localtime
    user: 1000:13000
    volumes:
      - /plex-stack-config/config/autobrr:/config
    networks:
      default:
        ipv4_address: 172.30.1.54
    # ports:
    # - 7474:7474

  omegabrr:
    container_name: omegabrr
    image: ghcr.io/autobrr/omegabrr:latest
    # ports:
    #   - "7441:7441"
    user: 1000:13000
    volumes:
      - /plex-stack-config/config/omegabrr:/config
    networks:
      default:
        ipv4_address: 172.30.1.55

  # qbitrr:
  #   image: feramance/qbitrr:latest
  #   user: 1000:1000 # Required to ensure the container is run as the user who has perms to see the 2 mount points and the ability to write to the CompletedDownloadFolder mount
  #   tty: true # Ensure the output of docker-compose logs qBitrr are properly colored.
  #   restart: unless-stopped
  #   # networks: This container MUST share a network with your Sonarr/Radarr instances
  #   environment:
  #     - TZ=Europe/London
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /plex-stack-config/config/qbitrr:/config # Config folder for qBitrr
  #     # TODO get correct output
  #     - /mnt/plex-stack/data/torrents/completed:/completed_downloads:rw # The script will ALWAYS require write permission in this folder if mounted, this folder is used to monitor completed downloads and if not present will cause the script to ignore downloaded file monitoring.
  #   # Now just to make sure it is clean, when using this script in a docker you will need to ensure you config.toml values reflect the mounted folders.
  #   # The same would apply to Settings.CompletedDownloadFolder
  #   # e.g CompletedDownloadFolder = /completed_downloads/folder/in/container

  #   logging: # this script will generate a LOT of logs - so it is up to you to decide how much of it you want to store
  #     driver: 'json-file'
  #     options:
  #       max-size: '50m'
  #       max-file: 3
  #   depends_on: # Not needed but this ensures qBitrr only starts if the dependencies are up and running
  #     - qbittorrent
  #   networks:
  #     default:
  #       ipv4_address: 172.30.1.14

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    user: 1000:13000 # optional but recommended
    volumes:
      - /plex-stack-config/config/cross-seed:/config
      - /mnt/plex-stack/data/torrents:/torrents:ro # your torrent clients .torrent cache, can and should be mounted read-only (e.g. qbit: `BT_Backup` | deluge: `state` | transmission: `transmission/torrents` | rtorrent: session dir from `.rtorrent.rc`)
      - /mnt/plex-stack/data/torrents/cross-seeds:/cross-seeds
      - /mnt/plex-stack/data/torrents:/data/torrents # OPTIONAL!!! this is location of your data (used for data-based searches or linking)
    command: 'daemon' # this enables the daemon, change to search to specifically run a search ONLY
    restart: 'unless-stopped' # make sure to not enable it in search mode, otherwise it will keep rerunning constantly
    network_mode: 'service:gluetun'
    depends_on:
      gluetun:
        condition: service_started
  #    networks:
  #     default:
  #      ipv4_address: 172.30.1.56

networks:
  default:
    external: true
    name: reverse-proxy
