# IP Range: 172.30.1.2-10
services:
  readarr_audio:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr_audio
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /plex-stack-config/config/readarr-config-audio:/config
      - /mnt/plex-stack/data:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.3

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - user=13014:13000
      - TZ=Europe/Amsterdam
    volumes:
      - /plex-stack-config/config/audiobookshelf:/config
      - /mnt/plex-stack/data/media/audiobooks:/audiobooks
      - /mnt/plex-stack/data/media/podcasts:/podcasts
      - /mnt/plex-stack/data/media/audiobookshelf-metadata:/metadata
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.4

  readarr_books:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr_books
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /plex-stack-config/config/readarr-config:/config
      - /mnt/plex-stack/data:/data
      - /plex-stack-config/config/calibre-config/calibre-library:/books
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.5

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /plex-stack-config/config/calibre-config:/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.6

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /plex-stack-config/config/calibre-web:/config
      - /plex-stack-config/config/calibre-config/calibre-library:/books
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.7

networks:
  default:
    external: true
    name: reverse-proxy
