# IP Range: 172.30.1.41-50
services:
  #region plex & co
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=13000
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /plex-stack-config/config/plex-docker:/config
      - /mnt/plex-stack/data/media:/media
      - /tmp/transcoding:/transcoding
    restart: unless-stopped
    network_mode: 'host'

  # plextraktsync:
  #   image: lscr.io/linuxserver-labs/plextraktsync:latest
  #   container_name: plextraktsync
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Amsterdam
  #   volumes:
  #     - /plex-stack-config/config/plextraktsync:/config
  #   restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/overseerr-config:/app/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.41

networks:
  default:
    # tracking highest ip assigment
    # 172.30.1.27
    external: true
    name: reverse-proxy
