services:
  #region network & monitoring
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /plex-stack-config/config/reverse-proxy-manager/data:/data
      - /plex-stack-config/config/reverse-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      default:
        ipv4_address: 172.30.1.12
      nextcloud-aio:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /plex-stack-config/config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.24

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - /plex-stack-config/config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    networks:
      default:
        ipv4_address: 172.30.1.25

  wyl:
    image: aceberg/watchyourlan:v2
    container_name: watch-your-lan
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ~/.dockerdata/wyl:/data/WatchYourLAN
    environment:
      TZ: Europe/Amsterdam # required: needs your TZ for correct time
      IFACES: 'enp1s0' # required: 1 or more interface
      HOST: '0.0.0.0' # optional, default: 0.0.0.0
      PORT: '8840' # optional, default: 8840
      TIMEOUT: '120' # optional, time in seconds, default: 120
      # SHOUTRRR_URL: '' # optional, set url to notify
      THEME: 'sand' # optional
      COLOR: 'dark' # optional

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=13000
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/tautulli-config:/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.10

  hardware-monitoring:
    image: nicolargo/glances:3.4.0.5-full
    container_name: hardware-monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      - 'GLANCES_OPT=-w'
    pid: host
    networks:
      default:
        ipv4_address: 172.30.1.26

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.32

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    network_mode: 'host'
    command: tunnel --no-autoupdate run --token eyJhIjoiYjg1MTA4NjA1YjJkMTc2YjgzN2JmNzc1OWI1ZjBhZDUiLCJ0IjoiYWIwMDQ4MzYtMzI3Zi00NjYxLThlZGItZTZmYmFhYWVkOWE4IiwicyI6IlltWmxZek0yWWpNdE1XWmpaaTAwTnpobExXSTVaVGd0T0dZM05ESXlNemd5TTJNdyJ9

  dns:
    restart: unless-stopped
    container_name: dns
    image: strm/dnsmasq
    volumes:
      - /plex-stack-config/config/dns/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    ports:
      - '54:53/udp'

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    #    env_file: /plex-stack-config/config/keycloak/.env
    container_name: keycloak
    command: start
    environment:
      KC_HOSTNAME: 'auth.theobeorodeo.rodeo'
      KC_PROXY: 'edge'
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/certs/privkey.pem
      KC_HTTPS_CERTIFICATE_FILE: /etc/certs/cert.pem
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /plex-stack-config/config/reverse-proxy-manager/letsencrypt/live/npm-17/fullchain.pem:/etc/certs/cert.pem
      - /plex-stack-config/config/reverse-proxy-manager/letsencrypt/live/npm-17/privkey.pem:/etc/certs/privkey.pem
    depends_on:
      - keycloak-db
    networks:
      default:
        ipv4_address: 172.30.1.50

  keycloak-db:
    env_file: /plex-stack-config/config/keycloak/.env
    container_name: keycloak-db
    image: postgres:10.1
    volumes:
      - /plex-stack-config/config/keycloak/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.30.1.51

  keycloak-db-backup:
    image: postgres:10.1
    container_name: keycloak-db-backup
    env_file: /plex-stack-config/config/keycloak/backup-db.env
    volumes:
      - /plex-stack-config/config/keycloak/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      default:
        ipv4_address: 172.30.1.52

networks:
  default:
    external: true
    name: reverse-proxy
  nextcloud-aio:
    external: true
    name: nextcloud-aio
