services:
  #region sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/sonarr-config:/config
      - /mnt/plex-stack/data:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.17

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/sonarr-config-anime:/config
      - /mnt/plex-stack/data:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.21

  #region radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr

    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/radarr-config:/config
      - /mnt/plex-stack/data:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.18
  radarr-anime:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-anime

    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/radarr-config-anime:/config
      - /mnt/plex-stack/data:/data

    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.22

  #region bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13013
      - PGID=13000
      - TZ=Europe/Amsterdam

    volumes:
      - /plex-stack-config/config/bazarr-config:/config
      - /mnt/plex-stack/data:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.7

  bazarr-anime:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-anime
    environment:
      - PUID=13013
      - PGID=13000
      - TZ=Europe/Amsterdam
    volumes:
      - /plex-stack-config/config/bazarr-anime-config:/config
      - /mnt/plex-stack/data:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.30.1.75

networks:
  default:
    external: true
    name: reverse-proxy
